Plant.create!([
  {latin_name: "Adenocalymma comosum", plant_habit: "Vine", life_cycle: "Perennial", sun_requirements: "Full Sun to Partial Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 10a -1.1 °C (30 °F) to +1.7 °C (35 °F)", maximum_recommended_zone: nil, plant_height: nil, plant_spread: nil, leaves: "Evergreen", flowers: "Showy", bloom_size: "2\"-3\"", underground_structures: "Taproot", suitable_locations: "Houseplant. Espalier", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Needs excellent drainage in pots", flower_color: "Yellow", flower_time: "Late winter or early spring. Spring. Late spring or early summer. Summer", wildlife_attractant: "Bees", image_url: "https://upload.wikimedia.org/wikipedia/commons/7/78/Adenocalymma_comosum_vine_%289268781913%29.jpg", soil_ph_preferences: nil, fruit: nil, commonname: "Yellow Trumpet Vine"},
  {latin_name: "Aspidistra grandiflora", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Partial or Dappled Shade. Partial Shade to Full Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 8b -9.4 °C (15 °F) to -6.7 °C (20 °F)", maximum_recommended_zone: "Zone 11", plant_height: "2 to 3 feet", plant_spread: "2 to 3 feet", leaves: "Evergreen. Broadleaf", flowers: "Showy", bloom_size: "4\"-5\"", underground_structures: "Rhizome", suitable_locations: "Xeriscapic. Houseplant", resistances: "Drought tolerant", propagation: "Other methods", containers: "Suitable in 3 gallon or larger. Needs excellent drainage in pots", flower_color: nil, flower_time: nil, wildlife_attractant: nil, image_url: "https://upload.wikimedia.org/wikipedia/commons/1/14/Aspidistra_grandiflora_0003.jpg", soil_ph_preferences: nil, fruit: nil, commonname: "Aspidistra"},
  {latin_name: "Adiantum hispidulum 'Bronze Venus'", plant_habit: "Fern", life_cycle: "Perennial", sun_requirements: "Partial or Dappled Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 8a -12.2 °C (10 °F) to -9.4 °C (15 °F)", maximum_recommended_zone: "Zone 11", plant_height: "12 to 18 inches", plant_spread: "12 to 24 inches", leaves: "Evergreen. Other", flowers: nil, bloom_size: nil, underground_structures: "Rhizome", suitable_locations: "Houseplant", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Needs excellent drainage in pots", flower_color: nil, flower_time: nil, wildlife_attractant: nil, image_url: "https://amazon.clikpic.com/ShadyPlants/images/Adiantum_pubesence.jpg", soil_ph_preferences: nil, fruit: nil, commonname: "'Bronze Venus' Rosy Maidenhair Fern"},
  {latin_name: "Adromischus cristatus 'Key Lime Pie'", plant_habit: "Herb/Forb. Cactus/Succulent", life_cycle: "Perennial", sun_requirements: "Full Sun. Full Sun to Partial Shade", water_preferences: nil, minimum_cold_hardiness: "Zone 9b -3.9 °C (25 °F) to -1.1 °C (30 °F)", maximum_recommended_zone: nil, plant_height: "4-8 inches", plant_spread: nil, leaves: "Evergreen", flowers: "Showy", bloom_size: "Under 1\"", underground_structures: nil, suitable_locations: "Xeriscapic. Houseplant", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Needs excellent drainage in pots", flower_color: "White", flower_time: "Late summer or early fall", wildlife_attractant: nil, image_url: "https://worldofsucculents.com/wp-content/uploads/2013/08/Adromischus-cristatus-Crinkle-Leaf-Plant3.jpg", soil_ph_preferences: nil, fruit: nil, commonname: "Crinkle Leaf Plant"},
  {latin_name: "Aechmea orlandiana subsp. belloi", plant_habit: nil, life_cycle: "Perennial", sun_requirements: "Full Sun to Partial Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 9b -3.9 °C (25 °F) to -1.1 °C (30 °F)", maximum_recommended_zone: "Zone 11", plant_height: nil, plant_spread: nil, leaves: "Evergreen", flowers: "Showy", bloom_size: nil, underground_structures: nil, suitable_locations: "Houseplant", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Needs excellent drainage in pots", flower_color: nil, flower_time: nil, wildlife_attractant: nil, image_url: " https://upload.wikimedia.org/wikipedia/commons/7/7f/Aechmea_orlandiana_Ensign_BotGardBln271207B.jpg", soil_ph_preferences: nil, fruit: nil, commonname: "Aechmea"},
  {latin_name: "Aloe 'Pink Blush'", plant_habit: "Cactus/Succulent", life_cycle: "Perennial", sun_requirements: "Full Sun", water_preferences: "Dry Mesic. Dry", minimum_cold_hardiness: nil, maximum_recommended_zone: nil, plant_height: "to 12 inches", plant_spread: "8-12 inches", leaves: "Evergreen. Variegated", flowers: "Showy", bloom_size: "Under 1\"", underground_structures: nil, suitable_locations: "Xeriscapic. Houseplant", resistances: nil, propagation: "Other methods", containers: "Needs excellent drainage in pots", flower_color: "Orange", flower_time: "Late winter or early spring. Spring. Winter", wildlife_attractant: "Hummingbirds", image_url: "https://worldofsucculents.com/wp-content/uploads/2016/10/Aloe-Pink-Blush-Pink-Blush-Aloe2-702x527.jpg", soil_ph_preferences: nil, fruit: "Dehiscent", commonname: "Aloe"},
  {latin_name: "Aloinopsis luckhoffii", plant_habit: "Cactus/Succulent", life_cycle: "Perennial", sun_requirements: "Full Sun. Full Sun to Partial Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 9a -6.7 °C (20 °F) to -3.9 °C (25 °F)", maximum_recommended_zone: "Zone 11", plant_height: "1 to 2 inches", plant_spread: "2 to 4 inches", leaves: "Evergreen. Other", flowers: "Showy", bloom_size: "1\"-2\"", underground_structures: "Taproot", suitable_locations: "Houseplant", resistances: "Drought tolerant", propagation: "Other methods", containers: "Needs excellent drainage in pots", flower_color: "Yellow. Other", flower_time: "Winter", wildlife_attractant: nil, image_url: "https://worldofsucculents.com/wp-content/uploads/2014/03/Aloinopsis-luckhoffii5-702x527.jpg", soil_ph_preferences: "Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3). Slightly alkaline (7.4 – 7.8)", fruit: nil, commonname: "Aloinopsis"},
  {latin_name: "Alsobia 'San Miguel'", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Full Sun to Partial Shade. Partial or Dappled Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 13 +15.6 °C (60 °F) to +21.1 °C (70 °F)", maximum_recommended_zone: nil, plant_height: "6 to 12 inches", plant_spread: "12 to 18 inches", leaves: "Evergreen", flowers: "Showy", bloom_size: "1\"-2\"", underground_structures: nil, suitable_locations: "Houseplant. Terrariums", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Suitable in 1 gallon. Suitable for hanging baskets. Needs excellent drainage in pots", flower_color: "White. Other", flower_time: "Spring. Late spring or early summer", wildlife_attractant: nil, image_url: "https://ich-mag-pflanzen.de/shop/images/product_images/popup_images/28780_0.JPG", soil_ph_preferences: "Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3)", fruit: nil, commonname: "Lace Flower Vine"},
  {latin_name: "Alternanthera Plum Dandy™", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Full Sun to Partial Shade. Partial or Dappled Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 10a -1.1 °C (30 °F) to +1.7 °C (35 °F)", maximum_recommended_zone: "Zone 11", plant_height: "12 to 16 inches", plant_spread: "12 to 18 inches", leaves: "Unusual foliage color. Other", flowers: "Inconspicuous", bloom_size: "Under 1\"", underground_structures: nil, suitable_locations: "Houseplant", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Needs excellent drainage in pots", flower_color: nil, flower_time: nil, wildlife_attractant: nil, image_url: "https://i.pinimg.com/originals/4a/05/c1/4a05c133df71e6272c480130f271ab19.jpg", soil_ph_preferences: "Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3)", fruit: nil, commonname: "Alternanthera"},
  {latin_name: "Amydrium zippelianum", plant_habit: "Herb/Forb. Vine", life_cycle: "Perennial", sun_requirements: "Partial or Dappled Shade. Partial Shade to Full Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 9b -3.9 °C (25 °F) to -1.1 °C (30 °F)", maximum_recommended_zone: "Zone 13", plant_height: "4 to 12 feet", plant_spread: nil, leaves: "Evergreen", flowers: nil, bloom_size: "3\\\"-4\\\"", underground_structures: nil, suitable_locations: "Houseplant", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Suitable in 3 gallon or larger", flower_color: nil, flower_time: nil, wildlife_attractant: nil, image_url: "https://guskin.me/life/3568/6.jpg", soil_ph_preferences: "Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3)", fruit: "Other", commonname: "Amydrium"},
  {latin_name: "Anthurium lappoanum", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Partial or Dappled Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 10a -1.1 °C (30 °F) to +1.7 °C (35 °F)", maximum_recommended_zone: "Zone 11", plant_height: "18 to 24 inches", plant_spread: "12 to 18 inches", leaves: "Evergreen", flowers: nil, bloom_size: nil, underground_structures: nil, suitable_locations: "Houseplant. Terrariums", resistances: "Humidity tolerant", propagation: nil, containers: "Needs excellent drainage in pots", flower_color: nil, flower_time: nil, wildlife_attractant: nil, image_url: "https://i.pinimg.com/originals/c1/9d/19/c19d19c7081a33720396def654f7bd67.jpg", soil_ph_preferences: nil, fruit: nil, commonname: "Anthurium"},
  {latin_name: "Ardisia guianensis", plant_habit: "Shrub", life_cycle: "Perennial", sun_requirements: "Partial or Dappled Shade. Partial Shade to Full Shade. Full Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 9a -6.7 °C (20 °F) to -3.9 °C (25 °F)", maximum_recommended_zone: "Zone 11", plant_height: nil, plant_spread: nil, leaves: "Evergreen", flowers: "Inconspicuous", bloom_size: "Under 1\\\"", underground_structures: "Rhizome", suitable_locations: "Houseplant", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Suitable in 3 gallon or larger. Needs excellent drainage in pots", flower_color: "Pink. Other", flower_time: "Summer", wildlife_attractant: "Bees. Birds", image_url: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Ardisia_wallichii_002.JPG", soil_ph_preferences: "Moderately acid (5.6 – 6.0). Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3)", fruit: "Showy. Edible to birds", commonname: nil},
  {latin_name: "Asparagus aethiopicus", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Full Sun to Partial Shade. Partial or Dappled Shade", water_preferences: "Mesic", minimum_cold_hardiness: nil, maximum_recommended_zone: nil, plant_height: "12 - 24 inches", plant_spread: "12 - 36 inches", leaves: "Evergreen. Other", flowers: "Showy", bloom_size: "Under 1\\\"", underground_structures: "Tuber", suitable_locations: "Houseplant", resistances: "Humidity tolerant. Drought tolerant", propagation: "Other methods", containers: "Needs excellent drainage in pots", flower_color: "White. Other", flower_time: "Spring", wildlife_attractant: nil, image_url: "https://images.wagwalkingweb.com/media/articles/dog/asparagus-fern-poisoning/asparagus-fern-poisoning.jpg", soil_ph_preferences: "Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3)", fruit: "Showy. Edible to birds. Other", commonname: "Sprengers Asparagus"},
  {latin_name: "Aspidistra sichuanensis 'Gold Lancer'", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Full Sun to Partial Shade. Partial or Dappled Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 7b -15 °C (5 °F) to -12.2 °C (10 °F)", maximum_recommended_zone: "Zone 9b", plant_height: "24 to 36 inches", plant_spread: "14 to 36 inches", leaves: "Evergreen", flowers: "Inconspicuous", bloom_size: nil, underground_structures: "Rhizome", suitable_locations: "Xeriscapic. Houseplant", resistances: "Humidity tolerant. Drought tolerant", propagation: nil, containers: "Needs excellent drainage in pots", flower_color: "Russet", flower_time: nil, wildlife_attractant: nil, image_url: "https://cdn.shopify.com/s/files/1/2602/3376/products/Aspidistra_Rawhide_8.30.10_4_1024x1024.JPG", soil_ph_preferences: nil, fruit: nil, commonname: nil},
  {latin_name: "Asplenium", plant_habit: "Fern", life_cycle: "Perennial", sun_requirements: "Full Sun to Partial Shade. Partial or Dappled Shade. Partial Shade to Full Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 5a -28.9 °C (-20 °F) to -26.1 °C (-15 °F)", maximum_recommended_zone: "Zone 10b", plant_height: "12 to 24 inches", plant_spread: "12 to 24 inches", leaves: "Evergreen", flowers: "Other", bloom_size: nil, underground_structures: nil, suitable_locations: "Houseplant", resistances: "Humidity tolerant", propagation: nil, containers: "Needs excellent drainage in pots", flower_color: nil, flower_time: nil, wildlife_attractant: "Butterflies", image_url: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Asplenium-detail.jpg", soil_ph_preferences: nil, fruit: nil, commonname: nil},
  {latin_name: "Begonia 'Canary Wing'", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Partial or Dappled Shade. Partial Shade to Full Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 10b +1.7 °C (35 °F) to +4.4 °C (40 °F)", maximum_recommended_zone: "Zone 11", plant_height: "12 - 18 inches", plant_spread: "12 - 24 inches", leaves: "Unusual foliage color. Evergreen. Other", flowers: "Showy", bloom_size: "Under 1\\\"", underground_structures: nil, suitable_locations: "Houseplant", resistances: "Deer Resistant. Humidity tolerant", propagation: "Other methods", containers: "Suitable in 3 gallon or larger. Suitable for hanging baskets. Needs excellent drainage in pots", flower_color: "Red", flower_time: "Year Round", wildlife_attractant: "Bees. Hummingbirds", image_url: "https://www.deco-style.ca/wp-content/uploads/2017/10/Begonia-Canary-Wing.jpg", soil_ph_preferences: "Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3)", fruit: nil, commonname: nil},
  {latin_name: "Belosynapsis ciliata", plant_habit: "Herb/Forb", life_cycle: nil, sun_requirements: "Partial or Dappled Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 12 +10 °C (50 °F) to +15.6 °C (60 °F)", maximum_recommended_zone: nil, plant_height: "6 to 8 inches", plant_spread: "18 to 24 inches", leaves: "Unusual foliage color. Evergreen. Other", flowers: "Showy", bloom_size: "Under 1\\\"", underground_structures: "Rhizome", suitable_locations: "Houseplant", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Suitable for hanging baskets. Needs excellent drainage in pots", flower_color: "Blue. Lavender. Pink", flower_time: nil, wildlife_attractant: nil, image_url: "http://www.phytoimages.siu.edu/users/pelserpb/9_9_12/9sep12a/Belosynapsis2.jpg", soil_ph_preferences: "Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3)", fruit: nil, commonname: nil},
  {latin_name: "Billbergia 'Breauteana'", plant_habit: nil, life_cycle: "Perennial", sun_requirements: "Full Sun to Partial Shade. Partial or Dappled Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 9a -6.7 °C (20 °F) to -3.9 °C (25 °F)", maximum_recommended_zone: "Zone 11", plant_height: nil, plant_spread: nil, leaves: "Evergreen", flowers: "Showy", bloom_size: "Under 1\\\"", underground_structures: nil, suitable_locations: "Houseplant", resistances: nil, propagation: "Other methods", containers: "Needs excellent drainage in pots", flower_color: nil, flower_time: nil, wildlife_attractant: nil, image_url: "http://www.bromeliad.org.au/pictures/Billbergia/buchholtzii_l.jpg", soil_ph_preferences: "Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3)", fruit: nil, commonname: nil},
  {latin_name: "Bouvardia 'Flamingo Pink'", plant_habit: "Shrub", life_cycle: "Perennial", sun_requirements: "Full Sun. Full Sun to Partial Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 9a -6.7 °C (20 °F) to -3.9 °C (25 °F)", maximum_recommended_zone: "Zone 11", plant_height: "24 to 36 inches", plant_spread: "12 to 18 inches", leaves: "Evergreen", flowers: "Showy. Fragrant. Other", bloom_size: "1\\\"-2\\\"", underground_structures: "Taproot", suitable_locations: "Houseplant", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Suitable in 3 gallon or larger. Needs excellent drainage in pots", flower_color: "Pink", flower_time: "Late spring or early summer. Summer. Late summer or early fall", wildlife_attractant: "Butterflies. Hummingbirds", image_url: "http://www.flowers.org.uk/wp-content/uploads/2012/03/Bouvardia.jpg", soil_ph_preferences: "Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3)", fruit: nil, commonname: nil},
  {latin_name: "Calandrinia", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Full Sun. Full Sun to Partial Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 9a -6.7 °C (20 °F) to -3.9 °C (25 °F)", maximum_recommended_zone: "Zone 11", plant_height: "12 to 18 inches", plant_spread: "18 to 24 inches", leaves: "Evergreen", flowers: "Showy", bloom_size: nil, underground_structures: "Taproot", suitable_locations: "Xeriscapic. Houseplant", resistances: "Drought tolerant", propagation: nil, containers: "Needs excellent drainage in pots", flower_color: nil, flower_time: nil, wildlife_attractant: "Bees. Butterflies", image_url: "https://worldofsucculents.com/wp-content/uploads/2017/04/Calandrinia.jpg", soil_ph_preferences: nil, fruit: nil, commonname: "Redmaids"},
  {latin_name: "Calathea", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Partial or Dappled Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 10b +1.7 °C (35 °F) to +4.4 °C (40 °F)", maximum_recommended_zone: "Zone 11", plant_height: "12 to 36 inches", plant_spread: "12 to 36 inches", leaves: "Evergreen. Variegated", flowers: "Inconspicuous", bloom_size: "Under 1\\\"", underground_structures: "Rhizome", suitable_locations: "Houseplant. Terrariums", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Suitable in 1 gallon. Suitable for hanging baskets. Needs excellent drainage in pots", flower_color: "Pink. Red. White", flower_time: nil, wildlife_attractant: nil, image_url: "https://static.fleur-ami.com//master/product/1/20283_calathea_080_001.jpg", soil_ph_preferences: nil, fruit: nil, commonname: nil},
  {latin_name: "Callisia cordifolia", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Full Sun. Full Sun to Partial Shade. Partial or Dappled Shade", water_preferences: nil, minimum_cold_hardiness: "Zone 8b -9.4 °C (15 °F) to -6.7 °C (20 °F)", maximum_recommended_zone: nil, plant_height: "under 6 inches", plant_spread: "indefinite", leaves: "Unusual foliage color. Other", flowers: "Showy", bloom_size: "Under 1\\\"", underground_structures: nil, suitable_locations: "Houseplant", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Suitable for hanging baskets. Needs excellent drainage in pots", flower_color: "White", flower_time: "Summer. Late summer or early fall. Fall", wildlife_attractant: nil, image_url: "https://i.ebayimg.com/images/i/302368616712-0-1/s-l1000.jpg", soil_ph_preferences: nil, fruit: nil, commonname: nil},
  {latin_name: "Canna Happy Carmnen", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Full Sun. Full Sun to Partial Shade", water_preferences: nil, minimum_cold_hardiness: "Zone 9a -6.7 °C (20 °F) to -3.9 °C (25 °F)", maximum_recommended_zone: "Zone 11", plant_height: "12 to 16 inches", plant_spread: nil, leaves: nil, flowers: "Showy", bloom_size: "6\\\"-12\\\"", underground_structures: "Rhizome", suitable_locations: "Houseplant", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Suitable in 3 gallon or larger", flower_color: "Red", flower_time: "Summer. Late summer or early fall", wildlife_attractant: nil, image_url: "https://www.rotex-flowerbulbs.com/userdata/artikelen/canna-cannasol-happy-carmen-2-3-eye-25-p-carton-9630-en-G.jpg", soil_ph_preferences: nil, fruit: nil, commonname: nil},
  {latin_name: "Chirita ophiopogoides", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Partial or Dappled Shade", water_preferences: "Mesic", minimum_cold_hardiness: nil, maximum_recommended_zone: nil, plant_height: nil, plant_spread: nil, leaves: "Evergreen", flowers: "Showy", bloom_size: "Under 1\\\"", underground_structures: nil, suitable_locations: "Houseplant. Terrariums", resistances: "Humidity tolerant", propagation: "Other methods", containers: "Needs excellent drainage in pots", flower_color: "Lavender", flower_time: nil, wildlife_attractant: nil, image_url: "https://c1.staticflickr.com/5/4665/26398282338_69ae019d09_b.jpg", soil_ph_preferences: nil, fruit: nil, commonname: nil},
  {latin_name: "Chrysanthemum 'Amiko Violet'", plant_habit: "Herb/Forb", life_cycle: "Perennial", sun_requirements: "Full Sun", water_preferences: nil, minimum_cold_hardiness: "Zone 5a -28.9 °C (-20 °F) to -26.1 °C (-15 °F)", maximum_recommended_zone: "Zone 8b", plant_height: "24 to 36 inches", plant_spread: "24 to 36 inches", leaves: nil, flowers: "Showy", bloom_size: nil, underground_structures: nil, suitable_locations: "Houseplant", resistances: nil, propagation: nil, containers: "Needs excellent drainage in pots", flower_color: "Pink. Other", flower_time: "Late summer or early fall. Fall", wildlife_attractant: nil, image_url: "https://i1.wp.com/www.vivercid.com/wp-content/uploads/2017/02/5105-Amiko-Violet-Chrysanthemum.jpg", soil_ph_preferences: "Slightly acid (6.1 – 6.5)", fruit: nil, commonname: nil},
  {latin_name: "Clitoria ternatea 'Double Blue Rose'", plant_habit: "Herb/Forb. Vine", life_cycle: "Perennial", sun_requirements: "Full Sun. Full Sun to Partial Shade", water_preferences: "Mesic", minimum_cold_hardiness: "Zone 9b -3.9 °C (25 °F) to -1.1 °C (30 °F)", maximum_recommended_zone: "Zone 11", plant_height: "6 to 10 feet", plant_spread: nil, leaves: nil, flowers: "Showy", bloom_size: "1\\\"-2\\\"", underground_structures: nil, suitable_locations: "Houseplant. Espalier", resistances: "Humidity tolerant", propagation: nil, containers: "Suitable in 3 gallon or larger. Suitable for hanging baskets. Needs excellent drainage in pots", flower_color: "Blue. Other", flower_time: "Late summer or early fall. Fall", wildlife_attractant: "Bees. Butterflies", image_url: "https://i.pinimg.com/originals/80/df/73/80df731e797aedda37e60c9b78de45b3.jpg", soil_ph_preferences: "Slightly acid (6.1 – 6.5). Neutral (6.6 – 7.3)", fruit: nil, commonname: nil}
])
Room.create!([
  {name: "New Room", user_id: 1, light: nil, temperature: nil, humidity: nil, flowers: nil},
  {name: nil, user_id: 4, light: nil, temperature: nil, humidity: nil, flowers: nil},
  {name: "new Room", user_id: 2, light: nil, temperature: nil, humidity: nil, flowers: nil},
  {name: "wsd", user_id: 5, light: "low", temperature: nil, humidity: "high", flowers: false},
  {name: "wsd", user_id: 5, light: "low", temperature: nil, humidity: "high", flowers: false},
  {name: "wsd", user_id: 5, light: "low", temperature: nil, humidity: "high", flowers: false},
  {name: "wsd", user_id: 5, light: "low", temperature: nil, humidity: "high", flowers: false},
  {name: "wsd", user_id: 5, light: "low", temperature: nil, humidity: "high", flowers: false},
  {name: "dude", user_id: 5, light: "low", temperature: nil, humidity: "high", flowers: false}
])
RoomPlant.create!([
  {room_id: 1, plant_id: 1},
  {room_id: 1, plant_id: 4},
  {room_id: 1, plant_id: 6},
  {room_id: 8, plant_id: 10},
  {room_id: 9, plant_id: 10}
])
User.create!([
  {name: "George", username: "George", password_digest: nil, email: "george@george.com", encrypted_password: "$2a$11$2naw9sC4qtHe1TH9jhIAbeyN/pWX.LwwdTJu0AEGfH14WXT28xktm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil},
  {name: "g", username: "g", password_digest: "$2a$10$rGdo/0zUpNfkyXa8PCSpeeI6Wi28fy0xMkAfqcdy.8cbr6QknYTjC", email: "g@gg.com", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil},
  {name: nil, username: "hkjher", password_digest: "$2a$10$FcDxIvb4BemtHdPeLqlC4O78aT58uxOvDRef60TeA7UU5S3IgOVQS", email: "", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil},
  {name: "NewUser", username: "newuser", password_digest: "$2a$10$FTisv6O5qu01qycnEc47y.oGsiB4kkiU/Xc5FywTuuGQCHzf07RtW", email: "newuser@user.com", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil},
  {name: "Sergio Neves", username: "serg", password_digest: "$2a$10$aleCuYfaIRrmqo.l6Hx5d.9ngrIRqF2A51DNGoa0TOHpmb0EP4Wry", email: "serneves@hotmail.com", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil}
])
